let songs_dict = [
    {
      "🦆": "✓",
      "Song": "Just Like Heaven",
      "Artist": "Cure",
      "Score": 4.7,
      "Year": 1987,
      "F. Genre(s)": "New Wave; Jangle Pop; Dream Pop; Post-Punk",
      "B. Genre(s)": "New Wave; Jangle Pop; Dream P0p; Post-Punk; Rock; Pop Rock; Alternative Rock",
      "Top descriptors": "love; ethereal; bittersweet; celebration; lush; happy; uplifting",
      "All descriptors": "love; ethereal; bittersweet; celebration; lush; happy; uplifting; starry night; passionate; sunny day; optimistic; twee; anthemic; poetic; energetic; Christmas; icy",
      "Comments": "The ultimate love song. Not necessarily the best love song (though it is damn close), but the one that covers the most ground, touching on everything from the chemical rush of the initial crush to the rosy honeymoon phases to the shipwrecked aftermath of losing someone dear, all on top of the dreamiest, most unabashedly elated instrumental in pop music. Finding salvation in heaven, only to be forsaken by an angel",
      "BM": "\"Dancing in the deepest oceans, twisting in the water, you're JUST LIKE A DREAM\" [cue heavenly piano] + \"And found myself alone, alone, alone above a raging sea. That stole the only girl I loved, and drowned her deep inside of me.\"",
      "CD": "2023-05-24",
      "Language": "English",
      "Alt. Song Name(s)": "",
      "Alt. Artist Name(s)": "",
      "Notes": "Seen live",
      "Attributes": "[Gtest]",
      "Owned": "$-iTunes",
      "Mixtape(s)": "Mx: Obscurity Knocks",
      "Added": "2020-12-31",
      "Alpha": "{ Cure } { F } { 1987 }",
      "Conc": "Cure - Just Like Heaven",
      "BC": "#cc0000",
      "TC": "#f4cccc"
    },
    {
      "🦆": "✓",
      "Song": "Falling",
      "Artist": "Julee Cruise",
      "Score": 4.5,
      "Year": 1989,
      "F. Genre(s)": "Ambient Pop; Dream Pop; Television Music",
      "B. Genre(s)": "Amb–ent P0p; Dream P0p; Television Music; Alternative Rock; Soundtrack; Descriptor Genres",
      "Top descriptors": "love; ethereal; lush; soft; uplifting; soothing; relaxation; passionate",
      "All descriptors": "love; ethereal; lush; soft; uplifting; soothing; relaxation; passionate; epic; late night; starry night; luxurious; mysterious; calm; peaceful; low energy",
      "Comments": "Even without the Twin Peaks assocation (I first heard and loved this song long before I started watching TP anyway), there's a haunted undercurrent to this song that uniquely tempers how much of a pure love song it would be otherwise. It's like they've been affected by something outright supernatural, and it's left ambiguous as to whether or not its clouding their doubtful thoughts or amplifying their faithful ones. Absolutely divine songwriting",
      "BM": "Every single climactic, built-up instance of \"Are we falling in looooooooooove\" is like a revelation",
      "CD": "2023-06-24",
      "Language": "English",
      "Alt. Song Name(s)": "",
      "Alt. Artist Name(s)": "",
      "Notes": "",
      "Attributes": "[Gtest]; [soundtrack]",
      "Owned": "$-download",
      "Mixtape(s)": "",
      "Added": "2020-12-31",
      "Alpha": "{ Julee Cruise } { H } { 1989 }",
      "Conc": "Julee Cruise - Falling",
      "BC": "#000000",
      "TC": "#f8b5c7"
    },
    {
      "🦆": "✓",
      "Song": "Feel Good Inc.",
      "Artist": "Gorillaz",
      "Score": 4.4,
      "Year": 2005,
      "F. Genre(s)": "Hip Hop; Alternative Rock; Rap Rock",
      "B. Genre(s)": "Hip Hop; Alternative Rock; Rap Rock",
      "Top descriptors": "catchy; light black; conscious; melancholic; bittersweet; urban",
      "All descriptors": "catchy; light black; conscious; melancholic; bittersweet; urban",
      "Comments": "",
      "BM": "",
      "CD": "",
      "Language": "English",
      "Alt. Song Name(s)": "",
      "Alt. Artist Name(s)": "",
      "Notes": "Seen live",
      "Attributes": "[Gtest]",
      "Owned": "$-GPM",
      "Mixtape(s)": "",
      "Added": "2020-12-31",
      "Alpha": "{ Gorillaz } { I } { 2005 }",
      "Conc": "Gorillaz - Feel Good Inc.",
      "BC": "#134f5c",
      "TC": "#ffffff"
    },
    {
      "🦆": "✓",
      "Song": "Teen Age Riot",
      "Artist": "Sonic Youth",
      "Score": 4.2,
      "Year": 1988,
      "F. Genre(s)": "Indie Rock",
      "B. Genre(s)": "Indie Rock; Alternative Rock",
      "Top descriptors": "epic; adventure; heavy; urban; protest; fight song; resolute",
      "All descriptors": "epic; adventure; heavy; urban; protest; fight song; resolute; violence; noisy; crime; uplifting; optimistic; anthemic; light black; aggressive; political; progressive; dense",
      "Comments": "",
      "BM": "",
      "CD": "",
      "Language": "English",
      "Alt. Song Name(s)": "",
      "Alt. Artist Name(s)": "",
      "Notes": "",
      "Attributes": "[Gtest]",
      "Owned": "$-vinyldl",
      "Mixtape(s)": "",
      "Added": "2020-12-31",
      "Alpha": "{ Sonic Youth } { K } { 1988 }",
      "Conc": "Sonic Youth - Teen Age Riot",
      "BC": "#445c38",
      "TC": "#ffffff"
    },
    {
      "🦆": "✓",
      "Song": "Do It Again",
      "Artist": "Steely Dan",
      "Score": 4.2,
      "Year": 1972,
      "F. Genre(s)": "J–zz-Rock; Yacht Rock",
      "B. Genre(s)": "J–zz-Rock; Yacht Rock; Soft Rock; Pop Rock",
      "Top descriptors": "catchy; lush; luxurious; urban; conscious; fun; crime",
      "All descriptors": "catchy; lush; luxurious; urban; conscious; fun; crime; sunny day; soft; pessimistic; violence; fight song; philosophical; Summer",
      "Comments": "",
      "BM": "",
      "CD": "",
      "Language": "English",
      "Alt. Song Name(s)": "",
      "Alt. Artist Name(s)": "",
      "Notes": "",
      "Attributes": "[Gtest]",
      "Owned": "$-download",
      "Mixtape(s)": "",
      "Added": "2020-12-31",
      "Alpha": "{ Steely Dan } { K } { 1972 }",
      "Conc": "Steely Dan - Do It Again",
      "BC": "#ffd966",
      "TC": "#000000"
    },
    {
      "🦆": "✓",
      "Song": "Let It Happen",
      "Artist": "Tame Impala",
      "Score": 4.1,
      "Year": 2015,
      "F. Genre(s)": "Synthpop; Psychedelic Pop",
      "B. Genre(s)": "Synthpop; Psychedelic Pop; Electronic",
      "Top descriptors": "epic; bittersweet; adventure; lush; catchy; existential; storm; progressive",
      "All descriptors": "epic; bittersweet; adventure; lush; catchy; existential; storm; progressive; ethereal; introspective; surreal; death; apocalypse; ominous",
      "Comments": "",
      "BM": "",
      "CD": "",
      "Language": "English",
      "Alt. Song Name(s)": "",
      "Alt. Artist Name(s)": "",
      "Notes": "",
      "Attributes": "[Gtest]",
      "Owned": "",
      "Mixtape(s)": "",
      "Added": "2020-12-31",
      "Alpha": "{ Tame Impala } { L } { 2015 }",
      "Conc": "Tame Impala - Let It Happen",
      "BC": "#741b47",
      "TC": "#d9d2e9"
    },
    {
      "🦆": "✓",
      "Song": "Vitamin C",
      "Artist": "Can",
      "Score": 4,
      "Year": 1972,
      "F. Genre(s)": "Krautrock; Exp–rimental Rock; Psychedelic Rock",
      "B. Genre(s)": "Krautrock; Exp–rimental Rock; Psychedelic Rock; Progressive Rock",
      "Top descriptors": "INC; fun; passionate; fight song; manic; complex",
      "All descriptors": "INC; fun; passionate; fight song; manic; complex; progressive; quirky",
      "Comments": "",
      "BM": "",
      "CD": "",
      "Language": "English",
      "Alt. Song Name(s)": "",
      "Alt. Artist Name(s)": "",
      "Notes": "",
      "Attributes": "[Gtest]",
      "Owned": "",
      "Mixtape(s)": "",
      "Added": "2020-12-31",
      "Alpha": "{ Can } { M } { 1972 }",
      "Conc": "Can - Vitamin C",
      "BC": "#000000",
      "TC": "#8fcf6c"
    },
    {
      "🦆": "✓",
      "Song": "Super Natural",
      "Artist": "Danny L Harle; ft. Carly Rae Jepsen",
      "Score": 4,
      "Year": 2016,
      "F. Genre(s)": "Electropop; Bubblegum Bass; Dance-Pop",
      "B. Genre(s)": "Electropop; Bubblegum Bass; Dance-Pop; Electronic; EDM",
      "Top descriptors": "happy; love; epic; uplifting; celebration; ethereal; anthemic",
      "All descriptors": "happy; love; epic; uplifting; celebration; ethereal; anthemic; triumphant; optimistic; fantasy; sunny day; passionate; party; futuristic; energetic",
      "Comments": "",
      "BM": "",
      "CD": "",
      "Language": "English",
      "Alt. Song Name(s)": "",
      "Alt. Artist Name(s)": "",
      "Notes": "",
      "Attributes": "[Gtest]",
      "Owned": "$-download",
      "Mixtape(s)": "",
      "Added": "2020-12-31",
      "Alpha": "{ Danny L Harle; ft. Carly Rae Jepsen } { M } { 2016 }",
      "Conc": "Danny L Harle; ft. Carly Rae Jepsen - Super Natural",
      "BC": "#000000",
      "TC": "#ff1e74"
    },
    {
      "🦆": "✓",
      "Song": "Heaven",
      "Artist": "DJ Sammy; Yanou",
      "Score": 3.5,
      "Year": 2002,
      "F. Genre(s)": "Euro-Trance; Vocal Trance",
      "B. Genre(s)": "Euro-Trance; Vocal Trance; EDM; Dance; Electronic",
      "Top descriptors": "happy; ethereal; energetic 100; love; anthemic; uplifting; triumphant",
      "All descriptors": "happy; ethereal; energetic 100; love; anthemic; uplifting; triumphant; optimistic; nostalgic; epic; passionate; celebration; party; sunny day; resolute; fantasy; catchy",
      "Comments": "",
      "BM": "",
      "CD": "",
      "Language": "English",
      "Alt. Song Name(s)": "",
      "Alt. Artist Name(s)": "",
      "Notes": "",
      "Attributes": "[collab]; [Gtest]",
      "Owned": "",
      "Mixtape(s)": "",
      "Added": "2020-12-31",
      "Alpha": "{ DJ Sammy; Yanou } { R } { 2002 }",
      "Conc": "DJ Sammy; Yanou - Heaven",
      "BC": "#fce5cd",
      "TC": "#000000"
    },
    {
      "🦆": "✓",
      "Song": "Two Weeks",
      "Artist": "FKA Twigs",
      "Score": 3.5,
      "Year": 2014,
      "F. Genre(s)": "Alternative R&B; Art Pop; Electronic",
      "B. Genre(s)": "Alternative R&B; Art Pop; Electronic; Contemporary R&B",
      "Top descriptors": "",
      "All descriptors": "",
      "Comments": "",
      "BM": "",
      "CD": "",
      "Language": "English",
      "Alt. Song Name(s)": "",
      "Alt. Artist Name(s)": "",
      "Notes": "",
      "Attributes": "[Gtest]",
      "Owned": "",
      "Mixtape(s)": "",
      "Added": "2020-12-31",
      "Alpha": "{ FKA Twigs } { R } { 2014 }",
      "Conc": "FKA Twigs - Two Weeks",
      "BC": "#79dfff",
      "TC": "#000000"
    },
    {
      "🦆": "✓",
      "Song": "Me Gustas Tu",
      "Artist": "GFRIEND",
      "Score": 3.5,
      "Year": 2015,
      "F. Genre(s)": "K-Pop; Dance-Pop",
      "B. Genre(s)": "K-Pop; Dance-Pop",
      "Top descriptors": "",
      "All descriptors": "",
      "Comments": "",
      "BM": "",
      "CD": "",
      "Language": "Korean",
      "Alt. Song Name(s)": "오늘부터 우리는",
      "Alt. Artist Name(s)": "여자친구",
      "Notes": "",
      "Attributes": "[Gtest]",
      "Owned": "$-GPM ( Not best quality )",
      "Mixtape(s)": "",
      "Added": "2020-12-31",
      "Alpha": "{ GFRIEND } { R } { 2015 }",
      "Conc": "GFRIEND - Me Gustas Tu",
      "BC": "#38761d",
      "TC": "#ffffff"
    },
    {
      "🦆": "✓",
      "Song": "秦皇岛",
      "Artist": "Omnipotent Youth Society",
      "Score": 3.8,
      "Year": 2010,
      "F. Genre(s)": "Art Rock; Progressive Rock; Indie Rock",
      "B. Genre(s)": "Art Rock; Progressive Rock; Indie Rock; Alternative Rock",
      "Top descriptors": "INC; melancholic; sad; pessimistic; epic; passionate; sulking",
      "All descriptors": "INC; melancholic; sad; pessimistic; epic; passionate; sulking",
      "Comments": "",
      "BM": "",
      "CD": "",
      "Language": "Chinese",
      "Alt. Song Name(s)": "Qinhuangdao",
      "Alt. Artist Name(s)": "万能青年旅店",
      "Notes": "",
      "Attributes": "[Gtest]",
      "Owned": "",
      "Mixtape(s)": "",
      "Added": "2022-07-03",
      "Alpha": "{ Omnipotent Youth Society } { O } { 2010 }",
      "Conc": "Omnipotent Youth Society - 秦皇岛",
      "BC": "#bf9000",
      "TC": "#ffffff"
    },
    {
      "🦆": "✓",
      "Song": "Farewell Transmission",
      "Artist": "Songs: Ohia",
      "Score": 3.9,
      "Year": 2003,
      "F. Genre(s)": "Alt-Country; Country Rock",
      "B. Genre(s)": "Alt-Country; C0untry Rock; Northern American Music; Regional Music",
      "Top descriptors": "",
      "All descriptors": "",
      "Comments": "",
      "BM": "",
      "CD": "",
      "Language": "English",
      "Alt. Song Name(s)": "",
      "Alt. Artist Name(s)": "Magnolia Electric Co.",
      "Notes": "",
      "Attributes": "[Gtest]",
      "Owned": "",
      "Mixtape(s)": "Mx: Gold Ranch",
      "Added": "2020-12-31",
      "Alpha": "{ Songs: Ohia } { N } { 2003 }",
      "Conc": "Songs: Ohia - Farewell Transmission",
      "BC": "#1c4587",
      "TC": "#efefef"
    },
    {
      "🦆": "✓",
      "Song": "Time Out of Mind",
      "Artist": "Steely Dan",
      "Score": 3.5,
      "Year": 1980,
      "F. Genre(s)": "Yacht Rock",
      "B. Genre(s)": "Yacht Rock; Soft Rock; Pop Rock",
      "Top descriptors": "",
      "All descriptors": "",
      "Comments": "",
      "BM": "",
      "CD": "",
      "Language": "English",
      "Alt. Song Name(s)": "",
      "Alt. Artist Name(s)": "",
      "Notes": "",
      "Attributes": "[Gtest]",
      "Owned": "$-CD Rip",
      "Mixtape(s)": "",
      "Added": "2021-12-23",
      "Alpha": "{ Steely Dan } { R } { 1980 }",
      "Conc": "Steely Dan - Time Out of Mind",
      "BC": "#d0e0e3",
      "TC": "#26887d"
    },
    {
      "🦆": "✓",
      "Song": "Take Me to the River (Live)",
      "Artist": "Talking Heads",
      "Score": 3.5,
      "Year": 1984,
      "F. Genre(s)": "New Wave; Post-Punk; Art Rock; Film Soundtrack",
      "B. Genre(s)": "New Wave; Post-Punk; Art Rock; Film Soundtrack; Descriptor Genres",
      "Top descriptors": "",
      "All descriptors": "",
      "Comments": "",
      "BM": "",
      "CD": "",
      "Language": "English",
      "Alt. Song Name(s)": "",
      "Alt. Artist Name(s)": "",
      "Notes": "",
      "Attributes": "[Gtest]; [live]; [soundtrack]",
      "Owned": "$-CD Rip",
      "Mixtape(s)": "",
      "Added": "2022-03-08",
      "Alpha": "{ Talking Heads } { R } { 1984 }",
      "Conc": "Talking Heads - Take Me to the River (Live)",
      "BC": "#000000",
      "TC": "#e06666"
    },
    {
      "🦆": "✓",
      "Song": "3 Summers",
      "Artist": "Jeff Rosenstock",
      "Score": 4.6,
      "Year": 2023,
      "F. Genre(s)": "Indie Rock; Power Pop",
      "B. Genre(s)": "Indie Rock; Power Pop; Alternative Rock; Pop Rock",
      "Top descriptors": "Summer; anthemic; nostalgic; progressive; introspective; melancholic; bittersweet; adventure; epic; conscious; political",
      "All descriptors": "Summer; anthemic; nostalgic; progressive; introspective; melancholic; bittersweet; adventure; epic; conscious; political; existential; philosophical; energetic; urban; sulking",
      "Comments": "A perfect encapsulation of that undercurrent of malaise that's been plaguing reality since the decade began, deftly covering issues of identity, inequality, activism, nostalgia & lost time, friendship, and burnout in the most cathartic way possible. Rosenstock taking his entire ethos and packing it into one last series finale-esque blaze of a song (though thankfully without actually being a series finale)",
      "BM": "\"I sat around and I watched the wind for three whole summers. An eternity lapsed as I swallowed attacks, and just held them in. I can’t be fixed, so I’m just achin’. ‘Cause the longer I go is the more that I know that I’m different than before. And you can’t help me ANYMOOOOOOOOOORE\"",
      "CD": "2024-01-15",
      "Language": "English",
      "Alt. Song Name(s)": "",
      "Alt. Artist Name(s)": "",
      "Notes": "Seen live",
      "Attributes": "[Gtest]",
      "Owned": "$-recordlabel",
      "Mixtape(s)": "",
      "Added": "2023-09-01",
      "Alpha": "{ Jeff Rosenstock } { G } { 2023 }",
      "Conc": "Jeff Rosenstock - 3 Summers",
      "BC": "#c01c67",
      "TC": "#ffd7ec"
    },
    {
      "🦆": "✓",
      "Song": "Whitewash",
      "Artist": "Buckethead",
      "Score": 3.5,
      "Year": 1998,
      "F. Genre(s)": "Downtempo; Trip Hop",
      "B. Genre(s)": "Downtempo; Trip Hop; Electronic",
      "Top descriptors": "INC; relaxation; ECM Style; soft; soothing",
      "All descriptors": "INC; relaxation; ECM Style; soft; soothing; mysterious",
      "Comments": "",
      "BM": "",
      "CD": "",
      "Language": "Instrumental",
      "Alt. Song Name(s)": "",
      "Alt. Artist Name(s)": "",
      "Notes": "",
      "Attributes": "[Gtest]",
      "Owned": "",
      "Mixtape(s)": "",
      "Added": "2023-08-26",
      "Alpha": "{ Buckethead } { R } { 1998 }",
      "Conc": "Buckethead - Whitewash",
      "BC": "#434343",
      "TC": "#b4a7d6"
    }
   ]

export default songs_dict